services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: mevn_backend_dev
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/test-db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - mongodb

  ext-api-service:
    build:
      context: ./ext-api-service
      dockerfile: Dockerfile.dev
    container_name: ext_api_service_dev
    ports:
      - "8081:8080"
    volumes:
      - ./ext-api-service:/app

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: mevn_frontend_dev
    ports:
      - "8080:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:3000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend

volumes:
  mongodb_data_dev:
